version: '3.8'

services:
  postgres:
    build:
      context: ./services/database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  accounts:
    build:
      context: ./
      dockerfile: ./services/accounts/Dockerfile
    command: ["npm", "run", "accounts:start:dev"]
    volumes:
      - ./:/app
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/accounts
    depends_on:
      - postgres

  chats:
    build:
      context: ./
      dockerfile: ./services/chats/Dockerfile
    command: ["npm", "run", "chats:start:dev"]
    volumes:
      - ./:/app
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/chats
    depends_on:
      - postgres

  messages:
    build:
      context: ./
      dockerfile: ./services/messages/Dockerfile
    command: ["npm", "run", "messages:start:dev"]
    volumes:
      - ./:/app
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/messages
    depends_on:
      - postgres

  orchestrator:
    build:
      context: ./
      dockerfile: ./services/orchestrator/Dockerfile
    command: ["npm", "run", "orchestrator:start:dev"]
    volumes:
      - ./:/app
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/orchestrator
    depends_on:
      - postgres

  posts:
    build:
      context: ./
      dockerfile: ./services/posts/Dockerfile
    command: ["npm", "run", "posts:start:dev"]
    volumes:
      - ./:/app
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/posts
    depends_on:
      - postgres

  rbac:
    build:
      context: ./
      dockerfile: ./services/rbac/Dockerfile
    command: ["npm", "run", "rbac:start:dev"]
    volumes:
      - ./:/app
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/rbac
    depends_on:
      - postgres

  users:
    build:
      context: ./
      dockerfile: ./services/users/Dockerfile
    command: ["npm", "run", "users:start:dev"]
    volumes:
      - ./:/app
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/users
    depends_on:
      - postgres

  web:
    build:
      context: ./
      dockerfile: ./services/web/Dockerfile
    command: ["npm", "run", "web:start:dev"]
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/web
    depends_on:
      - postgres

  authentication:
    build:
      context: ./
      dockerfile: ./services/authentication/Dockerfile
    command: ["npm", "run", "authentication:start:dev"]
    volumes:
      - ./:/app
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/authentication
    depends_on:
      - postgres
    ports:
      - 8888:8080

  authorization:
    build:
      context: ./
      dockerfile: ./services/authorization/Dockerfile
    command: ["npm", "run", "authorization:start:dev"]
    volumes:
      - ./:/app
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/auth
    depends_on:
      - postgres

  permify:
    image: permify/permify
    container_name: permify
    environment:
      PERMIFY_DATABASE_URI: postgres://admin:admin@postgres:5432/permify
      PERMIFY_DATABASE_ENGINE: postgres

volumes:
  postgres_data: