version: '3'

services:
  backend:
    build:
      context: ./server
    image: ludka76127alailsonko1500/messenger-clone-backend:latest
    depends_on:
      - database-mc
    command: ["yarn", "start:dev"]
    volumes:
      - ./server:/app
    env_file:
      - ./server/.env.docker
    deploy:
      mode: replicated
      replicas: 2

  nginx:
    image: ludka76127alailsonko1500/messenger-clone-proxy:latest
    build:
      context: ./nginx
    ports:
      - "4000:443"
    depends_on:
      - backend

  frontend:
    container_name: frontend
    build:
      context: ./web
    image: ludka76127alailsonko1500/messenger-clone-frontend:latest
    ports:
      - "3000:3000"
    command: ["yarn", "start"]
    depends_on:
      - backend
    volumes:
      - ./web:/app

  database-mc:
    container_name: database-mc
    build:
      context: ./database
    image: ludka76127alailsonko1500/messenger-clone-database:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_DATABASE: postgres
      POSTGRESQL_USER: postgres
      POSTGRESQL_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pg_data:/var/lib/postgresql/data

  database-replica-mc:
    container_name: database-replica-mc
    build:
      context: ./database-replica
    image: ludka76127alailsonko1500/messenger-clone-database-replica:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DATABASE_HOST_MASTER: database-mc
      DATABASE_PORT_MASTER: 5432
    depends_on:
      - database-mc

volumes:
  pg_data:
