version: '3.8'

services:
  postgres:
    build:
      context: ./services/database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  accounts:
    build:
      context: ./services/accounts
    command: ["npm", "run", "start:dev"]
    volumes:
      - ./services/accounts:/app
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/accounts
    depends_on:
      - postgres

  chats:
    build:
      context: ./services/chats
    command: ["npm", "run", "start:dev"]
    volumes:
      - ./services/chats:/app
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/chats
    depends_on:
      - postgres

  messages:
    build:
      context: ./services/messages
    command: ["npm", "run", "start:dev"]
    volumes:
      - ./services/messages:/app
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/messages
    depends_on:
      - postgres

  orchestrator:
    build:
      context: ./services/orchestrator
    command: ["npm", "run", "start:dev"]
    volumes:
      - ./services/orchestrator:/app
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/orchestrator
    depends_on:
      - postgres

  posts:
    build:
      context: ./services/posts
    command: ["npm", "run", "start:dev"]
    volumes:
      - ./services/posts:/app
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/posts
    depends_on:
      - postgres

  rbac:
    build:
      context: ./services/rbac
    command: ["npm", "run", "start:dev"]
    volumes:
      - ./services/rbac:/app
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/rbac
    depends_on:
      - postgres

  users:
    build:
      context: ./services/users
    command: ["npm", "run", "start:dev"]
    volumes:
      - ./services/users:/app
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/users
    depends_on:
      - postgres

  web:
    build:
      context: ./services/web
    command: ["npm", "run", "dev"]
    volumes:
      - ./services/web:/app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/web
    depends_on:
      - postgres

volumes:
  postgres_data: