apiVersion: v1
kind: Service
metadata:
  name: service-messenger-clone-backend
  namespace: alailsonko-dev
spec:
  selector:
    app: service-messenger-clone-backend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000