apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-messenger-clone-database
  labels:
    app: service-messenger-clone-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-messenger-clone-database
  template:
    metadata:
      labels:
        app: service-messenger-clone-database
    spec:
      containers:
      - name: service-messenger-clone-database
        imagePullPolicy: Always
        image: ludka76127alailsonko1500/messenger-clone-database:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRESQL_USER
          value: postgres
        - name: POSTGRESQL_PASSWORD
          value: postgres
        - name: POSTGRESQL_DATABASE
          value: postgres
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
          resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"