apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: postgres-scc
allowPrivilegedContainer: false
runAsUser:
  type: MustRunAs
  uid: 999
seLinuxContext:
  type: MustRunAs
fsGroup:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:alailsonko-dev:postgres